### ISSUE TITLE
FileMissing

### ISSUE THREAD

**Issue by BlueMyOcean** [alyssaq/3Dreconstruction#1]
when i ran the example.py,an error ocurred

Traceback (most recent call last):
  File "/home/ben/PyProjects/3Dreconstruction/example.py", line 9, in <module>
    import features
ImportError: No module named 'features'

it seems like the features.py is missing

**Comment by alyssaq** [comment]
Oops. Thanks for reporting.
I've added it to the repo and modified `example.py` to read the images from `img` folder.

**Comment by BlueMyOcean** [comment]
At first,i'm new to study 3d reconstruction,in cube_reconstruction.py,and your project is really good,and here i have a question about what's the differences between reconstruct_points and linear_triangulation?i don't know what the algorithm of reconstruct_points.

**Comment by BlueMyOcean** [comment]
and you use 'p1 = m1 * X and p2 = m2 * X. Solve AX = 0' this formula to get 3D points,but i found a different formula in triangulation, [https://www.cs.auckland.ac.nz/courses/compsci773s1c/lectures/CS773S1C-3DReconstruction.pdf](url)

**Comment by alyssaq** [comment]
Both `linear_triangulation` and `reconstruct_points`produce the same resultant matrix using different equations. They are both based on the expansion of the cross product and utilising the fact that vectors `p` and `m * X` are parallel. 
The slides you linked utilises the fact that the ray through the 3D point is orthogonal to the ray from the 3D points to the 2D image points and origin. Different set of equations but it will produce similar results since the underlying constraints are exactly the same. If you're up for it, seems like a good exercise to implement and verify.

Please see image below for explanation of the 2 equations. 
Eq A is `linear_triangulation`, which is in Hartley and Zisserman's book.  Ive written the derivation.
Eq B is `reconstruct_points`, which is the skew-symmetric matrix of 2D `pt`,  dot product with `m` the camera matrix.

![fullsizerender](https://user-images.githubusercontent.com/2819448/30519274-8f8c3722-9bc4-11e7-831f-9f4b582fe935.jpg)

**Comment by BlueMyOcean** [comment]
@alyssaq i express my appreciation of your help!i feel suddenly enlightened! i've taken a note already.And recently i get a new problem,after i reconstructed the 3d points,i've found that they might not in the same coordinate system. The reason i guess is  the Essential Matrix which is got by 8 points Algorithm are different,if i change all the E to the same value,it has no meaning at all,so how could i solve this problem?

**Comment by alyssaq** [comment]
Every pair of 2D images will have their own essential matrix. Camera 1 is always at the origin and then camera 2 is calculated based on the essential matrix. You'll have to apply additional transformations to get all 3D reconstructed set of points into the same view space.

**Comment by BlueMyOcean** [comment]
well, sounds kind of difficult.anyway ,i'll  have a try.

**Comment by BlueMyOcean** [comment]
Really thanks for your help
